---
kind: pipeline
type: docker
name: master

steps:
  - name: build
    pull: if-not-exists
    image: golang:latest
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
    commands:
      - go mod download
      - go build -o blog .

  - name: hub
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: dujigui/blog
      username:
        from_secret: hub_username
      password:
        from_secret: hub_password
    depends_on:
      - build

  - name: registry
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: registry.nullsfootprints.com/blog
      registry: registry.nullsfootprints.com
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    depends_on:
      - build

  - name: deploy
    pull: if-not-exists
    image: appleboy/drone-ssh
    environment:
      REGISTRY_USERNAME:
        from_secret: registry_username
      REGISTRY_PASSWORD:
        from_secret: registry_password
    settings:
      script_stop: true
      host:
        from_secret: deploy_host
      key:
        from_secret: deploy_key
      user: ubuntu
      envs:
        - registry_username
        - registry_password
      script:
        - export REGISTRY_URL=registry.nullsfootprints.com
        - export REGISTRY_REPO=$REGISTRY_URL/blog
        - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_URL
        - docker pull $REGISTRY_REPO:latest
        - docker rm -f blog || true
        - docker run --name blog --network blog -d $REGISTRY_REPO:latest
        - docker rmi $(docker images --filter reference=$REGISTRY_REPO --filter before=$REGISTRY_REPO:latest -q)
    depends_on:
      - registry

trigger:
  branch:
    - master
  event:
    - push


---
kind: pipeline
type: docker
name: dev

steps:
  - name: build
    pull: if-not-exists
    image: golang:latest
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
    commands:
      - go mod download
      - go build -o blog .

  - name: registry
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: registry.nullsfootprints.com/blog_dev
      registry: registry.nullsfootprints.com
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    depends_on:
      - build

  - name: deploy
    pull: if-not-exists
    image: appleboy/drone-ssh
    environment:
      REGISTRY_USERNAME:
        from_secret: registry_username
      REGISTRY_PASSWORD:
        from_secret: registry_password
      BLOG_DSN_DEV:
        from_secret: blog_dsn_dev
    settings:
      script_stop: true
      host:
        from_secret: deploy_host
      key:
        from_secret: deploy_key
      user: ubuntu
      envs:
        - registry_username
        - registry_password
        - blog_dsn_dev
      script:
        - export REGISTRY_URL=registry.nullsfootprints.com
        - export REGISTRY_REPO=$REGISTRY_URL/blog_dev
        - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_URL
        - docker pull $REGISTRY_REPO:latest
        - docker rm -f blog_dev || true
        - docker run -v /home/ubuntu/blog/dev/:/app/data/ -e BLOG_DSN=$BLOG_DSN_DEV --name blog_dev -d $REGISTRY_REPO:latest
        - docker network connect dev blog_dev
        - docker network connect nginx blog_dev
        - docker rmi $(docker images --filter reference=$REGISTRY_REPO --filter before=$REGISTRY_REPO:latest -q) || true
    depends_on:
      - registry

trigger:
  branch:
    - dev
  event:
    - push